-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgT7ON6iOlogi6wWU3
H2qpuLWyb5CdtOxtBCApiraEnrCgCgYIKoZIzj0DAQehRANCAAQ4NQr2wDiVrBYq
yxWGqAIrO2FKGiYr08hynmSEsQRc8eD0/96CkBkCRcvXGYX+x7ZwcoVbMHHpE57O
xt5BSDp3
-----END PRIVATE KEY-----