-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPxcRNt57L0SogoJI
uLxxrMd4jk0SCBOndJEe+FbGqyegCgYIKoZIzj0DAQehRANCAAQfJSDo3gDcU6Sj
qsUjHv0+RTEzniVsYhxFx+NPtdBm5fbP3rP8p6ltpCtJ4VsuvrPJke/+rfMdZEsJ
AEvujmLM
-----END PRIVATE KEY-----